M48
; DRILL file {KiCad 7.0.6} date Fri Jul 14 20:34:48 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-07-14T20:34:48-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X170.96Y-104.655
X170.96Y-109.505
T2
X173.99Y-104.355
X173.99Y-109.805
T0
M30
